### ISSUE TITLE
关于您公布的代码中，文件缺失的问题

### ISSUE THREAD

**Issue by SuperFanBin** [Suhan-Ling/Coarse-to-fine_Affordance#1]
尊敬的作者您好，很感谢你们开源的工作。但是我在复现的过程中发现，在文件 collect.py 中第 25 行引用的models.model_3d_w2a并不存在，请问可以在仓库中补充一下吗？十分感谢！

**Comment by wangyian-me** [comment]
I don't own this repo so I can't make any changes. But I recommend you to maybe copy [this](https://github.com/daerduoCarey/where2act/blob/main/code/models/model_3d.py) into models and rename it to `model_3d_w2a.py` and I think it will work.

**Comment by yanglh14** [comment]
I think it should be the legacy version in [model_3d_legacy.py](https://github.com/daerduoCarey/where2act/blob/main/code/models/model_3d_legacy.py)

**Comment by Suhan-Ling** [comment]
Thank you so much. I have added `./models.model_3d_w2a`.
